// src/utils/topicTitles.ts
export const topicTitles: Record<string, string> = {
    // ✅ Plumbing
    "level2-cold-water": "Cold Water",
    "level2-health-safety": "Health & Safety",
    "level2-common-principles": "Common Principles",
    "level2-central-heating": "Central Heating",
    "level2-drainage-sanitation": "Drainage & Sanitation",
    "level2-hot-water": "Hot Water",
    "level2-electrical": "Electrical",
    "level2-rainwater": "Rainwater",
    "level2-real-life-scenarios": "Real Life Scenarios",
    "level2-scientific-principles": "Scientific Principles",
    "cold-water": "Cold Water",
    "drainage-sanitation": "Drainage & Sanitation",
    "rainwater": "Rainwater",
    "environmental-technologies": "Environmental Technologies",
    "hot-water": "Hot Water",
    "central-heating": "Central Heating",
    "electrical": "Electrical",
    "domestic-fuels": "Domestic Fuels",
    "calculation-questions": "Calculation Questions",
  
    // ✅ Joinery
    "joinery-l2-health-safety": "Health & Safety in Construction",
    "joinery-l2-building-construction": "Building Construction Principles",
    "joinery-l2-communication": "Communication & Documentation",
    "joinery-l2-timber-technology": "Timber Technology",
    "joinery-l2-tools-equipment": "Tools & Equipment",
    "joinery-l2-materials": "Materials Knowledge",
    "joinery-l2-work-planning": "Work Planning & Preparation",
    "joinery-l3-health-safety": "Advanced Health & Safety",
    "joinery-l3-planning": "Planning & Organising Work",
    "joinery-l3-building-tech": "Advanced Building Technology",
    "joinery-l3-advanced-timber": "Advanced Timber Technology",
    "joinery-l3-surveying": "Site Surveying & Setting Out",
    "joinery-l3-joints-fixings": "Complex Joints & Fixings",
    "joinery-l3-building-regs": "Building Regulations & Standards",
    "joinery-l3-technical-communication": "Technical Communication",
    "joinery-l3-sustainability": "Environmental & Sustainability Awareness",
  
    // ✅ Bricklaying
    "bricklaying-l2-health-safety": "Health & Safety in Construction",
    "bricklaying-l2-building-construction": "Building Construction Principles",
    "bricklaying-l2-communication": "Communication & Documentation",
    "bricklaying-l2-materials": "Materials Science & Properties",
    "bricklaying-l2-blockwork-cavity": "Blockwork, Brickwork & Cavity Walls",
    "bricklaying-l2-setting-out": "Setting Out Masonry Structures",
    "bricklaying-l2-mortars": "Mixing & Using Mortars",
    "bricklaying-l2-tools-equipment": "Tools & Equipment",
    "bricklaying-l2-building-regs": "Building Regulations & Damp-Proofing",
    "bricklaying-l2-scaffolding": "Scaffolding Safety & Access Equipment",
    "bricklaying-l3-health-safety": "Advanced Health & Safety",
    "bricklaying-l3-masonry-structures": "Complex Masonry Structures",
    "bricklaying-l3-planning": "Planning & Organising Work",
    "bricklaying-l3-building-tech": "Advanced Building Technology",
    "bricklaying-l3-setting-out": "Setting Out for Complex Projects",
    "bricklaying-l3-structural-movement": "Structural Movement & Control Joints",
    "bricklaying-l3-conservation": "Conservation & Restoration Techniques",
    "bricklaying-l3-building-regs": "Building Regulations & Compliance",
    "bricklaying-l3-thermal-moisture": "Thermal & Moisture Protection Systems",
    "bricklaying-l3-sustainability": "Sustainability & Environmental Awareness",
  
    // ✅ HVAC
    "hvac-l2-health-safety": "Health & Safety",
    "hvac-l2-refrigeration": "Basic Refrigeration Principles",
    "hvac-l2-ventilation": "Ventilation Fundamentals",
    "hvac-l2-controls": "Controls & Instrumentation",
    "hvac-l2-pipework": "Pipework & Insulation",
    "hvac-l2-regulations": "Building Regulations",
    "hvac-l3-health-safety": "Advanced Health & Safety",
    "hvac-l3-system-design": "System Design & Planning",
    "hvac-l3-f-gas": "F-Gas Regulations",
    "hvac-l3-commissioning": "Commissioning & Testing",
    "hvac-l3-fault-finding": "Fault Diagnosis & Rectification",
    "hvac-l3-efficiency": "Energy Efficiency & Controls",
    "hvac-l3-regulations": "Environmental Regulations",
  
    // ✅ Gas
    "gas-domestic-safety": "Domestic Gas Safety",
    "gas-pipe-sizing": "Gas Pipe Sizing",
    "gas-ventilation-requirements": "Ventilation Requirements",
    "gas-flueing-requirements": "Flueing Requirements",
    "gas-appliance-types": "Gas Appliance Types",
    "gas-tightness-purging": "Tightness Testing & Purging",
    "gas-combustion-analysis": "Combustion Analysis",
    "gas-building-regulations": "Building Regulations (Part J)",
    "gas-unsafe-situations": "Unsafe Situations",
    "gas-emergency-procedures": "Emergency Procedures",
  
    // ✅ CSCS
    "cscs-hs-environment": "Health, Safety & Environment",
    "cscs-fire-prevention": "Fire Prevention & Control",
    "cscs-manual-handling": "Manual Handling",
    "cscs-hazardous-substances": "Hazardous Substances (COSHH)",
    "cscs-working-height": "Working at Height",
    "cscs-ppe": "Personal Protective Equipment (PPE)",
    "cscs-signage": "Safety Signs & Symbols",
    "cscs-first-aid": "First Aid & Emergency Procedures",
    "cscs-environmental-awareness": "Environmental Awareness",
    "cscs-behaviour": "Behavioural Case Studies",
  
    // ✅ Building Regs
    "regs-part-a": "Part A – Structure",
    "regs-part-b": "Part B – Fire Safety",
    "regs-part-c": "Part C – Site Preparation & Moisture",
    "regs-part-e": "Part E – Sound Insulation",
    "regs-part-f": "Part F – Ventilation",
    "regs-part-g": "Part G – Sanitation & Hot Water",
    "regs-part-h": "Part H – Drainage & Waste",
    "regs-part-j": "Part J – Combustion Appliances",
    "regs-part-k": "Part K – Protection from Falling",
    "regs-part-l": "Part L – Conservation of Power",
    "regs-part-m": "Part M – Access & Use",
    "regs-part-p": "Part P – Electrical Safety",
    "regs-part-q": "Part Q – Security",
    "regs-part-r": "Part R – Communications Infrastructure",
    "regs-part-s": "Part S – EV Charging",
  
      // ✅ Electrical
  "electrical-l2-health-safety": "Health & Safety",
  "electrical-l2-science-principles": "Electrical Science & Principles",
  "electrical-l2-installation-techniques": "Installation Methods & Techniques",
  "electrical-l2-wiring-systems": "Wiring Systems & Enclosures",
  "electrical-l2-building-regs": "Building Regulations (Part P)",
  "electrical-l2-circuit-design": "Basic Circuit Design",
  "electrical-l2-tools-materials": "Tools & Materials",
  "electrical-l2-cables-containment": "Cables & Containment",
  "electrical-l2-testing": "Initial Verification & Testing",
  "electrical-l3-health-safety": "Health & Safety",
  "electrical-l3-design": "Installation Design",
  "electrical-l3-science-principles": "Electrical Science & Principles",
  "electrical-l3-fault-diagnosis": "Fault Diagnosis & Rectification",
  "electrical-l3-inspection-testing": "Inspection & Testing",
  "electrical-l3-bs7671": "BS 7671 (18th Edition)",
  "electrical-l3-earthing-bonding": "Earthing & Bonding",
  "electrical-l3-three-phase": "Three-Phase Systems & Motors",
  "electrical-l3-circuit-calcs": "Circuit Design & Calculations",
  "electrical-l3-building-regs": "Building Regulations & Legal Compliance",
  "electrical-l3-renewables": "Renewables & Microgeneration",
  "electrical-l3-ev-charging": "EV Charging Installations",
  "electrical-l3-smart-tech": "Smart Technology Integration",
    
    };

  